### ISSUE TITLE
Can't upload save file.

### ISSUE THREAD

**Issue by Kartikal** [thomasmichaelwallace/lockepick#12]
Readme says "On the top bar use the 'Choose file' button to load your FF6 save file", but when you follow the link there is no such button there. 

There is an Upload button on the middle-right of the page which opens up a window but if you guide it to the save file through the window then after double-clicking the save file on the window, the window just disappears and the file doesn't get uploaded. 

What am I doing wrong?

P.S. I want to use this save editor to change characters' names. That is possible through this save editor, right?

**Comment by thomasmichaelwallace** [comment]
Hi @Kartikal !

Sorry for the confusion, I've updated the readme so it matches the names.

It sounds like you're doing the right thing, you can see a video of me uploading my save file and starting to edit it for comparison: https://recordit.co/o6oplJ5goy

This editor does support changing the names of characters, you'll find it in the "names" section for each file, so hopefully once we've worked out what's wrong with uploading, that bit should be easy.

If you can attach a copy of the file you're trying to upload, I can take a closer look. To do this on github:
 
- Press the [comment] button to start writing a response
- Zip up your save file (or just give it a '.zip' extension, or else github will reject it)
- Drag the file from your computer onto the comment writing area and it should upload it

**Comment by Kartikal** [comment]
Hi, I think the issue might have been on my end after all. I had only been doing quicksaves instead of saving at save points, maybe the editor doesn't work for those. I ended up just restarting my playthrough because I wasn't that far in, but this tool will be handy if I come across complications later down the line in my playthrough. Thank you for taking the time to create this!

**Comment by thomasmichaelwallace** [comment]
Not a problem - feel free to raise another issue if you have trouble again.

(aside: I'd definitely recommend saving normally too, quicksaves don't hold if you gameover.)

Have fun playing- it's a classic.
